### PR TITLE
Add option to use different postgame thread tags for wins and losses.…

### PR DESCRIPTION
**Pull request by toddrob99**
… Default to false (use single tag).

### CODE REVIEW

**Comment by toddrob99** [comment]
This allows reddit mods to apply different styling and thumbnails to postgame threads after wins and losses (and other results, which include postponements and ties). You can see the result in r/Philles: [win](https://redd.it/67yaxb), [loss](https://redd.it/66epzj), [other (postponed)](https://redd.it/67kk6y).

**Comment by toddrob99** [comment]
It says this pull request was merged, but I don't see the changes in mattabullock:master. Am I doing something wrong?

**Comment by mattabullock** [comment]
Woah, I'm fairly certain I didn't click merge on this one yet... this is odd.

**Comment by toddrob99** [comment]
There are a lot of changes for this one, so it'll take some time to re-submit. I have to make all the changes in a new branch.

**Comment by toddrob99** [comment]
Replaced with #33

**Pull request merged**
