### PR TITLE
Set suggested sort on pre and post threads

### PR DESCRIPTION
**Pull request by toddrob99**

### CODE REVIEW

**Comment by toddrob99** [comment]
This one also appears to have been phantom merged.

**Comment by toddrob99** [comment]
I think both #22 (this pull request) and #24 must have been "merged" when you merged #30. After that, I saw the Pull Requests tab change from 4 to 1. 

I also think #22 and #24 both had conflicts to resolve. 

Should I submit new pull requests for those changes, or are you able to re-open them?

**Comment by mattabullock** [comment]
Yeah I believe that's the case as well. I think you'll have to open new ones, but it may be difficult to get the changes to show in the diff again because they were already added... one way to find out!

**Comment by toddrob99** [comment]
Replaced with #32

**Pull request merged**
